use crate::anchor::{AccountTy, Constraint};
use crate::finding::{Finding, Severity};
use crate::rules::{Rule, RuleContext};

/// Field names that imply the account authorises the instruction.
/// Kept deliberately short: a missed unusual name costs nothing,
/// a false positive costs the user's trust.
const MARKERS: &[&str] = &[
    "authority",
    "admin",
    "owner",
    "signer",
    "payer",
    "delegate",
    "manager",
    "governance",
];

pub struct MissingSignerCheck;

/// Returns true if `name` equals `marker` exactly or ends with `_<marker>`.
fn matches_marker(name: &str, marker: &str) -> bool {
    name == marker || name.ends_with(&format!("_{marker}"))
}

/// Returns true if `field_name` appears as a whole identifier inside `seeds_text`.
///
/// We check for identifier boundaries so that `authority` is not matched inside
/// `authority_bump` or `pool_authority_seed`.
fn name_in_seeds(field_name: &str, seeds_text: &str) -> bool {
    let bytes = seeds_text.as_bytes();
    let n = field_name.len();
    let text = seeds_text;

    let mut start = 0;
    while let Some(pos) = text[start..].find(field_name) {
        let abs = start + pos;
        // Check left boundary: must be start of string or a non-identifier char.
        let left_ok = abs == 0 || {
            let c = text.as_bytes()[abs - 1] as char;
            !c.is_alphanumeric() && c != '_'
        };
        // Check right boundary: must be end of string or a non-identifier char.
        let right_ok = abs + n >= bytes.len() || {
            let c = bytes[abs + n] as char;
            !c.is_alphanumeric() && c != '_'
        };
        if left_ok && right_ok {
            return true;
        }
        start = abs + 1;
        if start >= text.len() {
            break;
        }
    }
    false
}

/// Returns true if a constraint establishes account identity — i.e., it does
/// more than mark writability or initialisation.
///
/// Identity-establishing:
///   `Seeds`  — Anchor derives and verifies the PDA address.
///   `HasOne` — Anchor verifies a stored pubkey on a related account.
///   `Custom` — an arbitrary boolean expression checked at runtime.
///   `Other`  with key `"signer"`, `"address"`, or a namespaced key (`::`)
///             such as `mint::authority`, `token::authority`.
///
/// NOT identity-establishing:
///   `Mut`  — marks writability only.
///   `Init` / `Bump` — lifecycle and PDA seed overhead; no identity claim.
///   `Other` with keys like `payer`, `space`, `close`, `realloc` — operational
///            metadata, not identity verification.
fn is_identity_establishing(c: &Constraint) -> bool {
    match c {
        Constraint::Seeds(_) | Constraint::HasOne(_) | Constraint::Custom(_) => true,
        Constraint::Other(k, _) => k == "signer" || k == "address" || k.contains("::"),
        Constraint::Mut | Constraint::Init | Constraint::Bump(_) => false,
    }
}

/// Returns true if the field holds a *deserialised* account — state the program
/// reads or writes through a named Rust type.
///
/// This is the signal that separates a real instruction context from a CPI
/// argument bundle.  A bundle describing another program's accounts (or an
/// autogenerated `native-to-anchor` stub) can only use raw `AccountInfo` /
/// `UncheckedAccount` / `Signer` / `Program` / `Sysvar`, because it has no type
/// for data it does not own.  A handler for this program almost always holds at
/// least one typed account — that state is why the instruction exists.
fn is_typed_state(ty: &AccountTy) -> bool {
    match ty {
        // `Account<'info, T>` and `InterfaceAccount<'info, T>`.
        AccountTy::Account(_) => true,
        // Zero-copy and legacy typed wrappers.
        AccountTy::Other(name) => matches!(
            name.as_str(),
            "AccountLoader" | "Loader" | "ProgramAccount" | "CpiAccount" | "ProgramState"
        ),
        _ => false,
    }
}

impl Rule for MissingSignerCheck {
    fn id(&self) -> &'static str {
        "VL001"
    }

    fn check(&self, ctx: &RuleContext<'_>, out: &mut Vec<Finding>) {
        for accounts in &ctx.anchor.accounts_structs {
            // Decide whether this struct is an instruction context for *this*
            // program at all.  Two independent signals put it in scope:
            //
            //   a) Some field holds typed state (`Account<'info, T>`,
            //      `AccountLoader<'info, T>`, …).  A CPI argument bundle for a
            //      foreign program cannot name such a type, so this is the
            //      cleanest separator — and it is what keeps VL001 alive on the
            //      canonical vulnerable withdraw, whose only constraint is `mut`.
            //
            //   b) Some field carries an identity-establishing constraint
            //      (`seeds`, `has_one`, `constraint`, `address`, `signer`, or a
            //      namespaced form).  A struct doing that work is validating
            //      account identity, so it is a context where an *un*validated
            //      authority is meaningful — even if every field is untyped.
            //
            // A struct with neither is a CPI bundle or an autogenerated native-
            // program wrapper: every account is the callee's to validate, and
            // `mut` / `init` / `bump` say nothing about which pubkey is required.
            let holds_typed_state = accounts.fields.iter().any(|f| is_typed_state(&f.ty));
            let has_identity_constraint = accounts
                .fields
                .iter()
                .any(|f| f.constraints.iter().any(is_identity_establishing));
            if !holds_typed_state && !has_identity_constraint {
                continue;
            }

            // Pre-compute: collect all constraint *values* from every field in
            // this struct.  This covers seeds texts, has_one targets, namespaced
            // constraints such as `mint::authority = mint_authority`, plain
            // `payer = authority`, and custom `constraint = ...` expressions.
            // A field is considered "pinned" if its name appears as a whole
            // identifier in any of these value strings — the same boundary check
            // used for seeds prevents `authority` from matching `authority_bump`.
            let all_constraint_values: Vec<&str> = accounts
                .fields
                .iter()
                .flat_map(|f| {
                    f.constraints.iter().filter_map(|c| match c {
                        Constraint::Seeds(v) | Constraint::HasOne(v) | Constraint::Custom(v) => {
                            Some(v.as_str())
                        }
                        Constraint::Other(_, v) if !v.is_empty() => Some(v.as_str()),
                        Constraint::Bump(Some(v)) => Some(v.as_str()),
                        _ => None,
                    })
                })
                .collect();

            for field in &accounts.fields {
                // Only flag AccountInfo / UncheckedAccount.
                if !matches!(
                    field.ty,
                    AccountTy::AccountInfo | AccountTy::UncheckedAccount
                ) {
                    continue;
                }

                // Name must match a marker exactly or with `_<marker>` suffix.
                if !MARKERS.iter().any(|m| matches_marker(&field.name, m)) {
                    continue;
                }

                // Check all forms of per-field validation — skip if any is present.

                // 1. `#[account(signer)]` → Other("signer", "")
                if field
                    .constraints
                    .iter()
                    .any(|c| matches!(c, Constraint::Other(k, _) if k == "signer"))
                {
                    continue;
                }

                // 2. `#[account(address = ...)]` → Other("address", value)
                if field
                    .constraints
                    .iter()
                    .any(|c| matches!(c, Constraint::Other(k, _) if k == "address"))
                {
                    continue;
                }

                // 3. Any `constraint = ...` → Custom(_)
                if field
                    .constraints
                    .iter()
                    .any(|c| matches!(c, Constraint::Custom(_)))
                {
                    continue;
                }

                // 3b. Field itself has `#[account(seeds = ..., bump)]` → it IS a
                //     PDA and Anchor validates the derivation.  A field name like
                //     `member_signer` that carries its own seeds constraint is not
                //     unvalidated — the runtime confirms the address at call time.
                if field
                    .constraints
                    .iter()
                    .any(|c| matches!(c, Constraint::Seeds(_)))
                {
                    continue;
                }

                // 4. Field name appears as a whole identifier in the value text of
                //    ANY constraint on ANY sibling field (seeds, has_one, payer =,
                //    mint::authority =, token::authority =, etc.).
                if all_constraint_values
                    .iter()
                    .any(|v| name_in_seeds(&field.name, v))
                {
                    continue;
                }

                out.push(ctx.finding(
                    self.id(),
                    Severity::High,
                    "missing signer check",
                    format!(
                        "`{}` is not validated. Any account can be passed here.",
                        field.name
                    ),
                    "Declare the field as `Signer<'info>`, add `#[account(signer)]`, \
                     `#[account(address = expected::ID)]`, a `constraint = ...`, \
                     or ensure it is pinned by a PDA's seeds or a `has_one`.",
                    field.span,
                ));
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rules::findings_for;

    // ── positive: bare authority-named AccountInfo with no constraints ────────
    //    The sibling vault has `seeds` (identity-establishing) so the struct is
    //    not skipped; `authority` carries no identity constraint → fires.

    #[test]
    fn flags_bare_authority_account_info() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(mut, seeds = [b"vault"], bump)]
                pub vault: Account<'info, Vault>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].rule_id, "VL001");
        assert!(findings[0].message.contains("authority"));
    }

    // ── positive: suffix matching (`pool_authority`) ─────────────────────────

    #[test]
    fn flags_pool_authority_suffix() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(mut, seeds = [b"vault"], bump)]
                pub vault: Account<'info, Vault>,
                pub pool_authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].rule_id, "VL001");
        assert!(findings[0].message.contains("pool_authority"));
    }

    // ── positive: `vault_authority` suffix ───────────────────────────────────

    #[test]
    fn flags_vault_authority_suffix() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Transfer<'info> {
                #[account(mut, seeds = [b"vault"], bump)]
                pub vault: Account<'info, Vault>,
                pub vault_authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert_eq!(findings.len(), 1);
    }

    // ── negative: `Signer<'info>` type — out of scope entirely ───────────────

    #[test]
    fn accepts_signer_typed_field() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                pub authority: Signer<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert!(findings.is_empty());
    }

    // ── negative: `#[account(signer)]` constraint ────────────────────────────

    #[test]
    fn accepts_account_signer_constraint() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(signer)]
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert!(findings.is_empty());
    }

    // ── negative: `#[account(address = ...)]` constraint ─────────────────────

    #[test]
    fn accepts_address_constraint() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(address = expected::ID)]
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert!(findings.is_empty());
    }

    // ── negative: `#[account(constraint = ...)]` constraint ──────────────────

    #[test]
    fn accepts_custom_constraint() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(constraint = authority.is_signer)]
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert!(findings.is_empty());
    }

    // ── negative: sibling `has_one = authority` ───────────────────────────────

    #[test]
    fn accepts_has_one_target() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(has_one = authority)]
                pub vault: Account<'info, Vault>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert!(findings.is_empty());
    }

    // ── negative: field name appears in sibling seeds ────────────────────────

    #[test]
    fn accepts_field_that_appears_in_seeds() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Initialize<'info> {
                #[account(seeds = [b"vault", authority.key().as_ref()], bump)]
                pub vault: Account<'info, Vault>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert!(findings.is_empty());
    }

    // ── negative: non-authority name is ignored ───────────────────────────────

    #[test]
    fn ignores_non_authority_name() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                pub price_feed: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert!(findings.is_empty());
    }

    // ── boundary: `authority_bump` must NOT match `_authority` or `authority` ─

    #[test]
    fn suffix_authority_bump_does_not_match() {
        // `authority_bump` ends with `_bump`, not `_authority`, so no match.
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                pub authority_bump: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert!(findings.is_empty());
    }

    // ── seeds identifier boundary: `authority_bump` in seeds must NOT suppress
    //    a bare `authority` field ────────────────────────────────────────────

    #[test]
    fn seeds_suppression_requires_identifier_boundary() {
        // seeds contain `authority_bump`, which includes `authority` as substring
        // but not as a whole identifier. So `authority` must still be flagged.
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(seeds = [b"vault", authority_bump.as_ref()], bump)]
                pub vault: Account<'info, Vault>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert_eq!(findings.len(), 1);
        assert!(findings[0].message.contains("authority"));
    }

    // ── unified Class 1: skip struct when no identity-establishing constraint ──
    //
    // Identity-establishing constraints: Seeds, HasOne, Custom (constraint = ...),
    // and Other(k, _) where k is "signer", "address", or contains "::".
    // Non-identity: Mut, Init, Bump — they say nothing about account identity.
    //
    // This unified rule replaces the old "no account attrs at all" heuristic.
    // A struct with only #[account(mut)] is a CPI account bundle or an
    // autogenerated native-program wrapper; the callee program validates identity.

    /// Positive: struct has an identity-establishing constraint (`seeds`) on a
    /// sibling field, so VL001 fires for the unconstrained `authority`.
    /// Differs from the negative below only in that `vault` has `seeds`.
    #[test]
    fn flags_authority_in_identity_constrained_struct() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Ctx<'info> {
                #[account(mut, seeds = [b"vault"], bump)]
                pub vault: Account<'info, Vault>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert_eq!(
            findings.len(),
            1,
            "expected exactly 1 finding, got {findings:?}"
        );
        assert!(findings[0].message.contains("authority"));
    }

    /// Negative: struct has ONLY `mut` constraints — no identity-establishing
    /// constraint on any field. VL001 must be silent (CPI wrapper / autogenerated stub).
    ///
    /// Guard removed: the identity-constraint check. When removed, VL001 fires
    /// for `authority` even though the struct is a pure CPI wrapper.
    #[test]
    fn accepts_mut_only_struct_even_with_authority_name() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct DexAccounts<'info> {
                #[account(mut)]
                pub market: UncheckedAccount<'info>,
                #[account(mut)]
                pub pc_vault: UncheckedAccount<'info>,
                pub sweep_authority: UncheckedAccount<'info>,
                pub vault_signer: UncheckedAccount<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert!(
            findings.is_empty(),
            "expected no findings for mut-only CPI wrapper, got {findings:?}"
        );
    }

    /// Negative: CPI-bundle struct — no field carries ANY #[account(...)]
    /// attribute. VL001 must be silent (the callee program validates).
    ///
    /// Guard removed: the identity-constraint check. When removed, VL001 fires
    /// for authority-named fields.
    #[test]
    fn accepts_cpi_bundle_struct_with_no_account_attrs() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct ApproveCollectionAuthority<'info> {
                pub collection_authority_record: AccountInfo<'info>,
                pub new_collection_authority: AccountInfo<'info>,
                pub update_authority: AccountInfo<'info>,
                pub payer: AccountInfo<'info>,
                pub metadata: AccountInfo<'info>,
                pub mint: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert!(
            findings.is_empty(),
            "expected no findings, got {findings:?}"
        );
    }

    /// Semantics moved in round 3.  Round 2 skipped this struct because its only
    /// constraints are `init` / `payer` / `space`, none of which establish
    /// identity.  That was wrong: `record` is typed state owned by this program,
    /// so this is a real instruction context and the unvalidated `authority` is
    /// exactly what VL001 exists to report.  The struct is now in scope and fires.
    ///
    /// The negative counterpart is `accepts_bare_init_only_untyped_struct` below,
    /// which differs by exactly one thing: `record` is untyped.
    #[test]
    fn flags_bare_init_struct_holding_typed_state() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct CreateRecord<'info> {
                #[account(init, payer = payer, space = 128)]
                pub record: Account<'info, Record>,
                #[account(mut)]
                pub payer: Signer<'info>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert_eq!(findings.len(), 1, "expected 1 finding, got {findings:?}");
        assert!(findings[0].message.contains("authority"));
    }

    /// Positive for the *second* in-scope clause: no field holds typed state,
    /// but `vault` carries `seeds` — the program validates a PDA by hand while
    /// leaving `authority` unchecked.  Differs from
    /// `accepts_mut_only_cpi_bundle_without_typed_state` by exactly the presence
    /// of the `seeds` constraint.
    #[test]
    fn flags_authority_in_untyped_struct_with_identity_constraint() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(mut, seeds = [b"vault"], bump)]
                /// CHECK: PDA verified by seeds
                pub vault: UncheckedAccount<'info>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert_eq!(findings.len(), 1, "expected 1 finding, got {findings:?}");
        assert!(findings[0].message.contains("authority"));
    }

    /// Negative: same bare-`init` shape with no typed state and no identity
    /// constraint — an autogenerated wrapper. VL001 must be silent.
    #[test]
    fn accepts_bare_init_only_untyped_struct() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct CreateRecord<'info> {
                #[account(init, payer = payer, space = 128)]
                pub record: AccountInfo<'info>,
                #[account(mut)]
                pub payer: Signer<'info>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert!(
            findings.is_empty(),
            "expected no findings for untyped bare-init struct, got {findings:?}"
        );
    }

    // ── in-scope signal: the struct owns typed program state ────────────────
    //
    // A CPI argument bundle for a foreign program, and an autogenerated
    // `native-to-anchor` stub, are built exclusively from `AccountInfo` /
    // `UncheckedAccount` / `Signer` / `Program` / `Sysvar` fields: they describe
    // *someone else's* accounts, so they cannot name a deserialised type.  A real
    // instruction context for this program almost always holds at least one typed
    // state account — that state is the reason the instruction exists.
    //
    // Presence of a typed state account therefore puts the struct in scope even
    // when no field carries an identity-establishing constraint.

    /// Positive: `Account<'info, Vault>` is present, so the struct is a real
    /// instruction context even though its only constraint is `mut`.
    /// Differs from `accepts_mut_only_cpi_bundle_without_typed_state` below by
    /// exactly one thing: the type of the `vault` field.
    #[test]
    fn flags_authority_when_struct_holds_typed_state_account() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(mut)]
                pub vault: Account<'info, Vault>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert_eq!(
            findings.len(),
            1,
            "expected exactly 1 finding, got {findings:?}"
        );
        assert!(findings[0].message.contains("authority"));
    }

    /// Negative: identical shape, but `vault` is an untyped `AccountInfo`, so no
    /// field holds typed state and no constraint establishes identity — a CPI
    /// argument bundle. VL001 must be silent.
    #[test]
    fn accepts_mut_only_cpi_bundle_without_typed_state() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(mut)]
                pub vault: AccountInfo<'info>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert!(
            findings.is_empty(),
            "expected no findings for untyped CPI bundle, got {findings:?}"
        );
    }

    /// Positive: zero-copy state is held through `AccountLoader`, which is just
    /// as much this program's own state as `Account`.
    #[test]
    fn flags_authority_when_struct_holds_account_loader_state() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(mut)]
                pub vault: AccountLoader<'info, Vault>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert_eq!(
            findings.len(),
            1,
            "expected exactly 1 finding, got {findings:?}"
        );
    }

    // ── regression: the three probe cases from the round-3 brief ────────────

    /// Case A — realistic vulnerable withdraw, no identity constraint anywhere.
    /// The typed `vault` puts the struct in scope; `authority` must fire.
    #[test]
    fn case_a_bare_authority_beside_typed_vault_fires() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct WithdrawA<'info> {
                #[account(mut)]
                pub vault: Account<'info, Vault>,
                /// CHECK: authority
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert_eq!(findings.len(), 1, "case A must fire, got {findings:?}");
        assert!(findings[0].message.contains("authority"));
    }

    /// Case B — the sibling `has_one` names `owner`, not `authority`, so
    /// `authority` remains unpinned and must fire (`owner` is pinned).
    #[test]
    fn case_b_has_one_on_sibling_pins_only_that_sibling() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct WithdrawB<'info> {
                #[account(mut, has_one = owner)]
                pub vault: Account<'info, Vault>,
                /// CHECK: authority
                pub authority: AccountInfo<'info>,
                /// CHECK: owner
                pub owner: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert_eq!(findings.len(), 1, "case B must fire once, got {findings:?}");
        assert!(findings[0].message.contains("authority"));
    }

    /// Case C — properly guarded: `has_one = authority` plus a `Signer` type.
    /// VL001 must be silent.
    #[test]
    fn case_c_has_one_plus_signer_type_is_silent() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct WithdrawC<'info> {
                #[account(mut, has_one = authority)]
                pub vault: Account<'info, Vault>,
                pub authority: Signer<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert!(
            findings.is_empty(),
            "case C must be silent, got {findings:?}"
        );
    }

    // ── class 2: namespaced constraint values pin the field ───────────────

    /// Positive: `authority` is NOT pinned by any constraint value →
    /// VL001 fires. Differs from the negative below only by removing the
    /// mint::authority line from the sibling constraint.
    #[test]
    fn flags_authority_not_referenced_in_constraint_values() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Ctx<'info> {
                #[account(init, mint::decimals = 6, payer = payer)]
                pub mint: Account<'info, Mint>,
                #[account(mut)]
                pub payer: Signer<'info>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert_eq!(findings.len(), 1);
        assert!(findings[0].message.contains("authority"));
    }

    /// Negative: `mint::authority = mint_authority` on a sibling field pins
    /// `mint_authority` — Anchor verifies the mint's authority equals that
    /// account at the program level. VL001 must be silent.
    ///
    /// Guard removed: name-in-any-constraint-value check. When removed the
    /// test fails because VL001 flags both `mint_authority` and
    /// `freeze_authority`.
    #[test]
    fn accepts_authority_pinned_by_namespaced_constraint_value() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct TestInitMintIfNeeded<'info> {
                #[account(init_if_needed, mint::decimals = 6,
                          mint::authority = mint_authority,
                          mint::freeze_authority = freeze_authority,
                          payer = payer)]
                pub mint: Account<'info, Mint>,
                #[account(mut)]
                pub payer: Signer<'info>,
                pub mint_authority: AccountInfo<'info>,
                pub freeze_authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert!(
            findings.is_empty(),
            "expected no findings, got {findings:?}"
        );
    }

    /// Negative: Anchor's legacy string-constraint syntax on a sibling field
    /// names `member_signer`, so the field IS validated at runtime.
    /// Differs from `flags_signer_not_covered_by_own_seeds` by the legacy
    /// constraint being the thing that names the field.
    #[test]
    fn accepts_authority_pinned_by_legacy_string_constraint() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct CreateMember<'info> {
                registrar: Box<Account<'info, Registrar>>,
                #[account(
                    "&balances.spt.owner == member_signer.key",
                    "balances.spt.mint == registrar.pool_mint"
                )]
                balances: BalanceSandboxAccounts<'info>,
                member_signer: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert!(
            findings.is_empty(),
            "expected no findings, got {findings:?}"
        );
    }

    // ── class 3: field with own seeds constraint is a PDA (validated) ────────

    /// Positive: `member_signer` has seeds on a *sibling* that don't contain
    /// its name → it IS unconstrained → must fire.
    /// The vault has `has_one` (identity-establishing) so the struct is not skipped.
    #[test]
    fn flags_signer_not_covered_by_own_seeds() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Stake<'info> {
                #[account(has_one = authority)]
                pub vault: Account<'info, Vault>,
                pub authority: Signer<'info>,
                pub member_signer: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert_eq!(findings.len(), 1);
        assert!(findings[0].message.contains("member_signer"));
    }

    /// Negative: `member_signer` itself carries `#[account(seeds = [...], bump)]`
    /// — Anchor verifies it equals the PDA, so it IS validated. VL001 silent.
    ///
    /// Guard removed: own-seeds check. When removed the test fails because
    /// VL001 flags `member_signer`.
    #[test]
    fn accepts_authority_field_with_own_seeds_constraint() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct ExecuteTransaction<'info> {
                pub registrar: Account<'info, Registrar>,
                #[account(
                    seeds = [registrar.to_account_info().key.as_ref(), member.to_account_info().key.as_ref()],
                    bump = member.nonce,
                )]
                pub member_signer: AccountInfo<'info>,
                pub member: Account<'info, Member>,
            }
        "#,
            &MissingSignerCheck,
        );
        assert!(
            findings.is_empty(),
            "expected no findings, got {findings:?}"
        );
    }

    // ── legacy: original test updated to include an identity-establishing ────
    //    constraint so the struct is not skipped by the unified guard.

    #[test]
    fn flags_an_unconstrained_authority_account() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(mut, seeds = [b"vault"], bump)]
                pub vault: Account<'info, Vault>,
                pub authority: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].rule_id, "VL001");
        assert_eq!(findings[0].line, 6);
        assert!(findings[0].message.contains("authority"));
    }

    #[test]
    fn accepts_a_signer_typed_authority() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                pub authority: Signer<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert!(findings.is_empty());
    }

    #[test]
    fn accepts_an_account_info_guarded_by_an_is_signer_constraint() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                #[account(constraint = admin.is_signer)]
                pub admin: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert!(findings.is_empty());
    }

    #[test]
    fn ignores_account_info_fields_without_an_authority_name() {
        let findings = findings_for(
            r#"
            #[derive(Accounts)]
            pub struct Withdraw<'info> {
                pub price_feed: AccountInfo<'info>,
            }
        "#,
            &MissingSignerCheck,
        );

        assert!(findings.is_empty());
    }
}
